"""Refactor

Revision ID: 4b5f7e0917d6
Revises: a7756a79dd0f
Create Date: 2023-01-17 01:27:55.946438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5f7e0917d6'
down_revision = 'a7756a79dd0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
