"""Refactor

Revision ID: 6ae9430c6f36
Revises: e8ce31261160
Create Date: 2023-01-17 01:50:53.191662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae9430c6f36'
down_revision = 'e8ce31261160'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
