"""Refactor

Revision ID: 71d02182ead6
Revises: 6ae9430c6f36
Create Date: 2023-01-17 01:58:16.763188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d02182ead6'
down_revision = '6ae9430c6f36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
