"""Refactor

Revision ID: a7756a79dd0f
Revises: 84fe5481c7f6
Create Date: 2023-01-17 00:39:18.978651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7756a79dd0f'
down_revision = '84fe5481c7f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
