"""Refactor

Revision ID: e8ce31261160
Revises: 4b5f7e0917d6
Create Date: 2023-01-17 01:37:48.290035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ce31261160'
down_revision = '4b5f7e0917d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
