"""first migration

Revision ID: 92923eb9b76f
Revises: 
Create Date: 2023-01-22 19:18:09.810301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92923eb9b76f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
