version: '3.8'

services:
  menu_app:
    container_name: menu-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: >
      sh -c "uvicorn main:app --reload"
    networks:
      - ylab_network
    ports:
      - "8000:8000"
    depends_on:
       - postgres_menu
    restart: always
  postgres_menu:
    container_name: postgres_menu
    image: postgres:15.1-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - ylab_network
    expose:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 3
networks:
  ylab_network:
    name: ylab_network